# Generated by Django 3.2.9 on 2021-12-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_hash',
        ),
    ]
